repository_type: pipeline

nf_core_version: 3.2.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-microcredential-nextflow-project_logo_light.png
    - docs/images/nf-core-microcredential-nextflow-project_logo_light.png
    - docs/images/nf-core-microcredential-nextflow-project_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  modules_config: false
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .editorconfig
    - .prettierignore
    - .prettierrc.yml
    - CITATIONS.md
    - assets/multiqc_config.yml
    - conf/base.config
    - conf/modules.config
    - modules.json
    - CHANGELOG.md
    - nextflow_schema.json
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .editorconfig
    - .prettierignore
    - .prettierrc.yml
    - CITATIONS.md
    - assets/multiqc_config.yml
    - conf/base.config
    - conf/modules.config
    - modules.json
    - CHANGELOG.md
    - nextflow_schema.json
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-microcredential-nextflow-project_logo_light.png
    - docs/images/nf-core-microcredential-nextflow-project_logo_light.png
    - docs/images/nf-core-microcredential-nextflow-project_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge
  nfcore_components: false
  schema_lint: false
  schema_params: false
  schema_description: false
  modules_json: false
  base_config: false

template:
  org: leenaput
  name: microcredential-nextflow-project
  description: 'As part of microcredentials, we will develop a Nextflow project for
    ONT data preprocessing and read mapping. '
  author: leenaput
  version: '1.0'
  force: true
  outdir: .
  skip_features:
    - ci
    - github_badges
    - code_linters
    - citations
    - gitpod
    - codespaces
    - multiqc
    - fastqc
    - modules
    - changelog
    - nf_schema
    - adaptivecard
    - slackreport
    - documentation
    - test_config
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
